# Generated by Django 2.2.3 on 2019-07-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(default=0, unique=True)),
                ('node_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('hasTmp', models.BooleanField(default=False)),
                ('hasHum', models.BooleanField(default=False)),
                ('hasLgt', models.BooleanField(default=False)),
                ('hasSnd', models.BooleanField(default=False)),
                ('hasVlt', models.BooleanField(default=False)),
                ('hasAmp', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Nodes',
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='NodeReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('light', models.IntegerField(default=0)),
                ('sound', models.IntegerField(default=0)),
                ('voltage', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Node')),
            ],
            options={
                'verbose_name_plural': 'Node Readings',
                'db_table': 'node_readings',
            },
        ),
    ]
